"""add-country-to-author

Revision ID: 22449fe1fd5a
Revises: df1368bba561
Create Date: 2024-03-24 01:09:16.556628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22449fe1fd5a'
down_revision: Union[str, None] = 'df1368bba561'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('country', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authors', 'country')
    # ### end Alembic commands ###
